### ISSUE TITLE
Does SIAB_SUDO=true works? 

### ISSUE THREAD

**Issue by giper45** [fhuegli/docker-shellinabox#2]
I'm trying to add a new user and give him sudo privilege. My Dockerfile is the following: 
```
FROM fhuegli/shellinabox:latest
ENV SIAB_GROUP=student SIAB_USER=student SIAB_PASSWORD=student
ENV SIAB_SUDO=true
```
I'm able to connect with student username, but when I do sudo su it says that I'm not in sudoers users... Am I wrong something?
Thanks in advance

**Comment by fhuegli** [comment]
The sudoers entry for wheel group was missing in /etc/sudoers.
